name: Quasar.LiveAi
favicon: null
layout_spectrum: 0.38545810361392796
typography_spectrum: 0.76755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004785'
    - '#fff0db'
    - '#693b3f'
    - '#d54d48'
  brandStrength: 0
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.0739182576071471
purpose: []
